env:
  browser: true
  es2021: true
  node: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: off
  no-plusplus: off
  no-unused-vars:
  - 'error'
  - varsIgnorePattern: ^_
    argsIgnorePattern: ^_
overrides:
  - files:
    - '**/*.test.js'
    env:
      jest: true
